import Head from "next/head";
import Image from "next/image";

import { DefaultLayout } from "layouts";

import { Inter } from "@next/font/google";
import styles from "styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Centro Pokémon - Página Inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <main className={styles.main}>
          <Image
            fill
            alt="Hero Image"
            style={{ objectFit: "cover" }}
            src="/images/pokemon-hero.jpg"
          />

          <div className={styles.description}>
            <h2 className={inter.className}>
              Cuidamos bem do seu pokémon, para ele cuidar bem de você
            </h2>
          </div>
        </main>
      </DefaultLayout>
    </>
  );
}
